In [2]:
import numpy as np
import pandas as pd 

import torch
from torch_geometric.data import HeteroData, Data
from torch_geometric.loader import LinkLoader, LinkNeighborLoader, NeighborLoader
import torch_geometric.transforms as T
from torch_geometric.nn import SAGEConv, to_hetero
from torch import Tensor

In [77]:
# Node feature matrix of shape [num_nodes, num_node_features]
# 5 nodes, each with a single feature
x = torch.tensor([[1], [2], [3], [4], [5]], dtype=torch.float)

# Edge indices (edges between nodes)
# For example, edges: (0->1), (1->2), (2->3), (3->4), (4->0)
edge_index = torch.tensor([
    [0, 1, 2, 3, 4],
    [1, 2, 3, 4, 0]
], dtype=torch.long)

# Edge labels (arbitrary labels for each edge)
# For instance, labeling edges as [0, 1, 2, 3, 4]
edge_label = torch.tensor([0, 1, 2, 3, 4], dtype=torch.long)

# Create the PyG Data object
data = Data(x=x, edge_index=edge_index, edge_label=edge_label)

In [78]:
transform = T.RandomLinkSplit(
    num_val=0.50,  # 10% validation edges
    num_test = 0,
    disjoint_train_ratio=0.3,  # 30% of training edges used for supervision
    # edge_types=("user", "rates", "movie"),  # Edge type
    # rev_edge_types=("movie", "rev_rates", "user"),  # Reverse edge type
)

train_data, val_data, _ = transform(data)

In [79]:
train_data

Data(x=[5, 1], edge_index=[2, 3], edge_label=[6], edge_label_index=[2, 6])

In [80]:
train_data.edge_label

tensor([1, 3, 5, 0, 0, 0])

In [81]:
train_data.edge_label_index

tensor([[0, 2, 4, 3, 3, 2],
        [1, 3, 0, 1, 0, 4]])

In [72]:
train_data.edge_label_index

tensor([[2, 4, 3, 3],
        [3, 0, 2, 0]])

In [73]:
val_data.edge_label_index

tensor([[1, 0, 0, 4],
        [2, 1, 4, 2]])

In [74]:
val_data.edge_label

tensor([1., 1., 0., 0.])